### PR TITLE
petswapper. works. tested on hypixel

### PR DESCRIPTION
**Pull request by osamabeinglagging**
Works. tested on hypixel. test it urself if you dont believe me. im sleepy thats why im so cranky. if you dont like my code, live with it. thank you. i love you. no i dont im kidding. ping me if something breaks. ill fix when im online

### CODE REVIEW

**Comment by TomJuri** [comment]
Maybe you could make some debug log messages more clear, for example "starting pet swapper" instead of just "starting" also remove OsamaClient lmao. Oh and you need to resolve the conflicts so it's actually mergeable

**Comment by NotInfiniteVelocityXvi** [comment]
i dislike this pull request, please deny it and block the user who made it, thanks :)

**Comment by osamabeinglagging** [comment]
> Maybe you could make some debug log messages more clear, for example "starting pet swapper" instead of just "starting" also remove OsamaClient lmao. Oh and you need to resolve the conflicts so it's actually mergeable

Done... thank you <3

**Comment by nekiak** [comment]
> i dislike this pull request, please deny it and block the user who made it, thanks :)

refrain from making useless comments

**Comment by nekiak** [comment]
Closing

**Pull request closed without merging**
