### PR TITLE
Fixed Discord Invite Link

### PR DESCRIPTION
**Pull request by AltoGoldfilled**

### CODE REVIEW

**Comment by TomJuri** [comment]
Actually it's not jellylabs anymore it's jellylab without the s

**Comment by AltoGoldfilled** [comment]
😭

**Comment by TomJuri** [comment]
Yeah just change that real quick and then it's mergeable

**Review by TomJuri — APPROVED** [review]

**Comment by nekiak** [comment]
Don't use vanity

**Pull request closed without merging**
