### PR TITLE
adding black cat 420 speed melon/pumpkin macro

### PR DESCRIPTION
**Pull request by NXlSChrona**
I think I added stuff in the right areas to make it work? It should just ride off the already existing melon/pumpkin macro just with a different pitch. I threw something into the drop drown and added an if/else based on what's selected in the gui.

Incase an explanation is appreciated, the black cat 420 speed melon/pumpkin farms are what people like melonkingde are currently using to set new records in contests. I will link a video showing the farm, it is a build guide though, so you may want to skip around a bit to actually look at it. https://www.youtube.com/watch?v=FH7Vm3d6icA

Also here's someone else asking for this type, https://discord.com/channels/997464259170680923/1131165120207278080

i don't want to add spam to the progress channel, I'll try to get IntelliJ and fix stuff once my dad gets home and I can get him to put in a password.

### CODE REVIEW

**Comment by TomJuri** [comment]
Hello, foremost, thank you for your pull request. However, the CI is failing on your fork because of some basic mistakes. It seems like you made all your changes on the GitHub website, consider getting and IDE like IntelliJ, so you get Syntax Highlighting and compiler errors directly when writing the code.

**Comment by wtfismyname69420** [comment]
gooogoooogaaagaaa

**Comment by TomJuri** [comment]
As you can see here 
https://github.com/NXlSChrona/FarmHelper/actions/runs/5598703382/jobs/10238702287 the compilation is still failing because you tried to add a double to a float, read the logs get an IDE and you can fix it!

**Comment by wtfismyname69420** [comment]
gooogoooogaaagaaa

**Comment by TomJuri** [comment]
Now its no longer failing, download the artifact and test it i guess

**Comment by NXlSChrona** [comment]
It does not work curently, I will definitely be messing with it later tonight once i can get IntelliJ. Thank you for your help TomJuri.

**Pull request closed without merging**
